// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBshEpbiE6JemK8s2xEpFODKPX6zCk8E',
    appId: '1:289942201224:android:788f30aca1369f96cb103d',
    messagingSenderId: '289942201224',
    projectId: 'recipegenerator-5d7ab',
    databaseURL: 'https://recipegenerator-5d7ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipegenerator-5d7ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqo0iHHqLjCQpzQ_fdp0MNUIqPfIobkhA',
    appId: '1:289942201224:ios:bb4db27993a2b1e8cb103d',
    messagingSenderId: '289942201224',
    projectId: 'recipegenerator-5d7ab',
    databaseURL: 'https://recipegenerator-5d7ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipegenerator-5d7ab.appspot.com',
    iosClientId: '289942201224-vpieiqfsh016uhcilfruhi7qe6d4h607.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomRecipeGenerator',
  );
}
